USE [master]
GO

/****** Object:  Database [Livraria]    Script Date: 31/05/2021 17:53:05 ******/
CREATE DATABASE [Livraria]  

go
use Livraria
GO

ALTER DATABASE [Livraria] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Livraria] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Livraria] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Livraria] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Livraria] SET ARITHABORT OFF 
GO

ALTER DATABASE [Livraria] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Livraria] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Livraria] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Livraria] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Livraria] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Livraria] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Livraria] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Livraria] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Livraria] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Livraria] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Livraria] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Livraria] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Livraria] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Livraria] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Livraria] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Livraria] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Livraria] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Livraria] SET RECOVERY FULL 
GO

ALTER DATABASE [Livraria] SET  MULTI_USER 
GO

ALTER DATABASE [Livraria] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Livraria] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Livraria] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Livraria] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Livraria] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Livraria] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Livraria] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Livraria] SET  READ_WRITE 
GO


